name: Build

on:
  push:
    paths-ignore:
      - '*.md'

  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '*.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Required by GitVersion
          fetch-depth: 0

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: dotnet build --configuration Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

  update-submodule:
    needs: build
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        repository:
          - horoscope-dev/Dalamud.Divination.Template
          - horoscope-dev/Dalamud.Divination.TwitterIntegration
          # - horoscope-dev/Dalamud.Divination.AetheryteLinkInChat
          - horoscope-dev/Dalamud.Divination.DiscordIntegration
          - horoscope-dev/Dalamud.Divination.PowerUtils
          - horoscope-dev/Dalamud.Divination.Calculator
          - horoscope-dev/Dalamud.Divination.Voiceroid2Talker
          - horoscope-dev/Dalamud.Divination.Debugger
          # - horoscope-dev/Dalamud.Divination.Craftsman
          # - horoscope-dev/Dalamud.Divination.Fisherman
          - horoscope-dev/Dalamud.Divination.SseClient
          - horoscope-dev/Dalamud.Divination.ChatFilter
          # - horoscope-dev/Dalamud.Divination.InstanceIDViewer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repository }}
          path: repo/${{ matrix.repository }}
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Update Submodules
        working-directory: repo/${{ matrix.repository }}
        run: |
          git submodule foreach git reset --hard
          git submodule foreach git pull origin master
          git submodule foreach git checkout master
          git submodule foreach git pull origin master
          git submodule foreach git checkout master

      - name: Prepare Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          cwd: repo/${{ matrix.repository }}
          default_author: github_actions
          message: Update Common to ${{ steps.short-sha.outputs.sha }}
