name: Build

env:
  DALAMUD_ZIP_URL: https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

on:
  push:

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Required by GitVersion
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri ${{ env.DALAMUD_ZIP_URL }} -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: dotnet build --configuration Release
